version: '3.7'

services:
  pandacare:
    image: keiradiaz/pandacare:latest
    container_name: pandacare
    ports: 
      - "8080:80"
    environment:
      - DB_URL=jdbc:postgresql://panda-care-db.cjhwe3715lop.us-east-1.rds.amazonaws.com:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=pandacare
      - JWT_SECRET_KEY=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources